CREATE SEQUENCE S_MASACH_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MAPHIEUNHAPSACH_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MAHOADON_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MAPHIEUTHU_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MAKHACHHANG_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MADAUSACH_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MATHELOAI_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE SEQUENCE S_MATACGIA_ID
	MINVALUE 1
	NOMAXVALUE
	INCREMENT BY 1
	START WITH 1
	NOCACHE
	NOORDER
	NOCYCLE;

CREATE TABLE THELOAI (
	MaTheLoai NUMBER(8,0) NOT NULL,
	TenTheLoai NVARCHAR2(50) NOT NULL
);

INSERT INTO THELOAI(MaTheLoai, TenTheLoai) 
VALUES (S_MATHELOAI_ID.nextval, 'Văn Học');

INSERT INTO THELOAI(MaTheLoai, TenTheLoai) 
VALUES (S_MATHELOAI_ID.nextval, 'Kỹ năng sống');

INSERT INTO THELOAI(MaTheLoai, TenTheLoai) 
VALUES (S_MATHELOAI_ID.nextval, 'Khoa học');

INSERT INTO THELOAI(MaTheLoai, TenTheLoai) 
VALUES (S_MATHELOAI_ID.nextval, 'Hồi ký');

INSERT INTO THELOAI(MaTheLoai, TenTheLoai) 
VALUES (S_MATHELOAI_ID.nextval, 'Thiếu nhi');

CREATE TABLE TACGIA (
	MaTacGia NUMBER(8,0) NOT NULL,
	TenTacGia NVARCHAR2(50) NOT NULL, 
	NamSinh NUMBER(4,0)
);

INSERT INTO TACGIA(MaTacGia, TenTacGia, NamSinh) 
VALUES (S_MATACGIA_ID.nextval, 'Vãn Tình', 1967);

INSERT INTO TACGIA(MaTacGia, TenTacGia, NamSinh) 
VALUES (S_MATACGIA_ID.nextval, 'Dale Carnegie', 1966);

INSERT INTO TACGIA(MaTacGia, TenTacGia, NamSinh) 
VALUES (S_MATACGIA_ID.nextval, 'Paulo Coelho', 1672);

INSERT INTO TACGIA(MaTacGia, TenTacGia, NamSinh) 
VALUES (S_MATACGIA_ID.nextval, 'Mễ Mông', 1987);

INSERT INTO TACGIA(MaTacGia, TenTacGia, NamSinh) 
VALUES (S_MATACGIA_ID.nextval, 'Cảnh Thiên', 1986);

CREATE TABLE DAUSACH (
	MaDauSach NUMBER(8,0) NOT NULL,
	TenDauSach NVARCHAR2(100) NOT NULL,
	MaTheLoai NUMBER(8,0) NOT NULL
);

INSERT INTO DAUSACH(MaDauSach, TenDauSach, MaTheLoai) 
VALUES (S_MADAUSACH_ID.nextval, 'Bạn Đắt Giá Bao Nhiêu?', 1);

INSERT INTO DAUSACH(MaDauSach, TenDauSach, MaTheLoai) 
VALUES (S_MADAUSACH_ID.nextval, 'Đắc Nhân Tâm', 1);

INSERT INTO DAUSACH(MaDauSach, TenDauSach, MaTheLoai) 
VALUES (S_MADAUSACH_ID.nextval, 'Nhà Giả Kim', 1);

INSERT INTO DAUSACH(MaDauSach, TenDauSach, MaTheLoai) 
VALUES (S_MADAUSACH_ID.nextval, 'Sống Thực Tế Giữa Đời Thực Dụng', 1);

INSERT INTO DAUSACH(MaDauSach, TenDauSach, MaTheLoai) 
VALUES (S_MADAUSACH_ID.nextval, 'Đừng Lựa Chọn An Nhàn Khi Còn Trẻ', 1);

CREATE TABLE CHITIETTACGIA (
	MaTacGia NUMBER(8,0) NOT NULL,
	MaDauSach NUMBER(8,0) NOT NULL
);

INSERT INTO CHITIETTACGIA(MaTacGia, MaDauSach) 
VALUES (1,1);

INSERT INTO CHITIETTACGIA(MaTacGia, MaDauSach) 
VALUES (2,2);

INSERT INTO CHITIETTACGIA(MaTacGia, MaDauSach) 
VALUES (3,3);

INSERT INTO CHITIETTACGIA(MaTacGia, MaDauSach) 
VALUES (4,4);

INSERT INTO CHITIETTACGIA(MaTacGia, MaDauSach) 
VALUES (5,5);

CREATE TABLE SACH (
	MaSach 	NUMBER(8,0) NOT NULL,
	MaDauSach NUMBER(8,0) NOT NULL,
	NhaXuatBan NVARCHAR2(50),
	NamXuatBan NUMBER(4,0),
	SoLuongTon NUMBER(8,0) NOT NULL,
	DonGiaBan NUMBER(12, 0) NOT NULL
);

INSERT INTO SACH(MaSach, MaDauSach, NhaXuatBan, NamXuatBan, SoLuongTon, DonGiaBan) 
VALUES (S_MASACH_ID.nextval, 1, 'Bloom Books', 2010, 100, 200000);

INSERT INTO SACH(MaSach, MaDauSach, NhaXuatBan, NamXuatBan, SoLuongTon, DonGiaBan) 
VALUES (S_MASACH_ID.nextval, 2, 'First News - Trí Việt', 2011, 100, 400000);

INSERT INTO SACH(MaSach, MaDauSach, NhaXuatBan, NamXuatBan, SoLuongTon, DonGiaBan) 
VALUES (S_MASACH_ID.nextval, 3, 'Nhã Nam', 2014, 100, 500000);

INSERT INTO SACH(MaSach, MaDauSach, NhaXuatBan, NamXuatBan, SoLuongTon, DonGiaBan) 
VALUES (S_MASACH_ID.nextval, 4, 'Vibooks', 2015, 100, 100000);

INSERT INTO SACH(MaSach, MaDauSach, NhaXuatBan, NamXuatBan, SoLuongTon, DonGiaBan) 
VALUES (S_MASACH_ID.nextval, 5, 'GuBooks', 2014, 100, 30000);

CREATE TABLE PHIEUNHAPSACH (
	MaPhieuNhapSach NUMBER(8,0) NOT NULL,
	NgayLap DATE NOT NULL,
	TongTien NUMBER(12,0) NOT NULL
);

INSERT INTO PHIEUNHAPSACH(MaPhieuNhapSach, NgayLap, TongTien)
VALUES (S_MAPHIEUNHAPSACH_ID.nextval, to_date('28/08/2019','dd/mm/yyyy'), 20000000);

INSERT INTO PHIEUNHAPSACH(MaPhieuNhapSach, NgayLap, TongTien)
VALUES (S_MAPHIEUNHAPSACH_ID.nextval, to_date('28/08/2019','dd/mm/yyyy'), 40000000);

INSERT INTO PHIEUNHAPSACH(MaPhieuNhapSach, NgayLap, TongTien)
VALUES (S_MAPHIEUNHAPSACH_ID.nextval, to_date('28/08/2019','dd/mm/yyyy'), 50000000);

INSERT INTO PHIEUNHAPSACH(MaPhieuNhapSach, NgayLap, TongTien)
VALUES (S_MAPHIEUNHAPSACH_ID.nextval, to_date('28/08/2019','dd/mm/yyyy'), 10000000);

INSERT INTO PHIEUNHAPSACH(MaPhieuNhapSach, NgayLap, TongTien)
VALUES (S_MAPHIEUNHAPSACH_ID.nextval, to_date('28/08/2019','dd/mm/yyyy'), 3000000);

CREATE TABLE CHITIETPHIEUNHAPSACH (
	MaPhieuNhapSach NUMBER(8,0) NOT NULL,
	MaSach NUMBER(8,0) NOT NULL,
	SoLuong NUMBER(8,0) NOT NULL,
	DonGiaNhap NUMBER(12,0) NOT NULL,
	ThanhTien NUMBER(12,0) NOT NULL
);

INSERT INTO CHITIETPHIEUNHAPSACH(MaPhieuNhapSach, MaSach, SoLuong, DonGiaNhap, ThanhTien)
VALUES (1,1,100,200000,20000000);

INSERT INTO CHITIETPHIEUNHAPSACH(MaPhieuNhapSach, MaSach, SoLuong, DonGiaNhap, ThanhTien)
VALUES (2,2,100,400000,40000000);

INSERT INTO CHITIETPHIEUNHAPSACH(MaPhieuNhapSach, MaSach, SoLuong, DonGiaNhap, ThanhTien)
VALUES (3,3,100,500000,50000000);

INSERT INTO CHITIETPHIEUNHAPSACH(MaPhieuNhapSach, MaSach, SoLuong, DonGiaNhap, ThanhTien)
VALUES (4,4,100,100000,10000000);

INSERT INTO CHITIETPHIEUNHAPSACH(MaPhieuNhapSach, MaSach, SoLuong, DonGiaNhap, ThanhTien)
VALUES (5,5,100,30000,3000000);

CREATE TABLE KHACHHANG (
	MaKhachHang NUMBER(8,0) NOT NULL,
	HoTen NVARCHAR2(50) NOT NULL,  
	DienThoai NVARCHAR2(15),
	DiaChi NVARCHAR2(100),
	Email NVARCHAR2(50),
	TongNo NUMBER(12,0) NOT NULL
);

INSERT INTO KHACHHANG(MaKhachHang, HoTen, DienThoai, DiaChi, Email, TongNo)
VALUES (S_MAKHACHHANG_ID.nextval,'Trần Văn A','0914226322','HCM City','a@gmail.com',0);

INSERT INTO KHACHHANG(MaKhachHang, HoTen, DienThoai, DiaChi, Email, TongNo)
VALUES (S_MAKHACHHANG_ID.nextval,'Trần Văn B','0914226311','HCM City','b@gmail.com',0);

INSERT INTO KHACHHANG(MaKhachHang, HoTen, DienThoai, DiaChi, Email, TongNo)
VALUES (S_MAKHACHHANG_ID.nextval,'Trần Văn C','0914226344','HCM City','c@gmail.com',0);

INSERT INTO KHACHHANG(MaKhachHang, HoTen, DienThoai, DiaChi, Email, TongNo)
VALUES (S_MAKHACHHANG_ID.nextval,'Trần Văn D','0914226355','HCM City','d@gmail.com',0);

INSERT INTO KHACHHANG(MaKhachHang, HoTen, DienThoai, DiaChi, Email, TongNo)
VALUES (S_MAKHACHHANG_ID.nextval,'Trần Văn E','0914226333','HCM City','e@gmail.com',0);

CREATE TABLE HOADON (
	MaHoaDon NUMBER(8,0) NOT NULL,
	NgayLap DATE NOT NULL,
	MaKhachHang NUMBER(8,0) NOT NULL,
	TongTien NUMBER(12,0) NOT NULL,
	SoTienTra NUMBER(12,0) NOT NULL
);

INSERT INTO HOADON(MaHoaDon, NgayLap, MaKhachHang, TongTien, SoTienTra)
VALUES (S_MAHOADON_ID.nextval, to_date('22/02/2020','dd/mm/yyyy'), 1, 210000, 210000);

INSERT INTO HOADON(MaHoaDon, NgayLap, MaKhachHang, TongTien, SoTienTra)
VALUES (S_MAHOADON_ID.nextval, to_date('22/02/2020','dd/mm/yyyy'), 1, 420000, 420000);

INSERT INTO HOADON(MaHoaDon, NgayLap, MaKhachHang, TongTien, SoTienTra)
VALUES (S_MAHOADON_ID.nextval, to_date('22/02/2020','dd/mm/yyyy'), 1, 525000, 525000);

INSERT INTO HOADON(MaHoaDon, NgayLap, MaKhachHang, TongTien, SoTienTra)
VALUES (S_MAHOADON_ID.nextval, to_date('22/02/2020','dd/mm/yyyy'), 1, 105000, 100000);

INSERT INTO HOADON(MaHoaDon, NgayLap, MaKhachHang, TongTien, SoTienTra)
VALUES (S_MAHOADON_ID.nextval, to_date('22/02/2020','dd/mm/yyyy'), 1, 31500, 31500);

CREATE TABLE CHITIETHOADON (
	MaHoaDon NUMBER(8,0) NOT NULL,
	MaSach NUMBER(8,0) NOT NULL,
	SoLuong NUMBER(8,0) NOT NULL,
	DonGia NUMBER(12,0) NOT NULL,
	ThanhTien NUMBER(12,0) NOT NULL
);

INSERT INTO CHITIETHOADON(MaHoaDon, MaSach, SoLuong, DonGia, ThanhTien)
VALUES (1,1,1,200000,210000);

INSERT INTO CHITIETHOADON(MaHoaDon, MaSach, SoLuong, DonGia, ThanhTien)
VALUES (2,2,1,400000,420000);

INSERT INTO CHITIETHOADON(MaHoaDon, MaSach, SoLuong, DonGia, ThanhTien)
VALUES (3,3,1,500000,525000);

INSERT INTO CHITIETHOADON(MaHoaDon, MaSach, SoLuong, DonGia, ThanhTien)
VALUES (4,4,1,100000,105000);

INSERT INTO CHITIETHOADON(MaHoaDon, MaSach, SoLuong, DonGia, ThanhTien)
VALUES (5,5,1,30000,31500);

CREATE TABLE PHIEUTHU (
	MaPhieuThu NUMBER(8,0) NOT NULL,
	MaKhachHang NUMBER(8,0) NOT NULL,
	NgayLap DATE NOT NULL,
	SoTienThu NUMBER(12,0) NOT NULL
);

INSERT INTO PHIEUTHU(MaPhieuThu, MaKhachHang, NgayLap, SoTienThu)
VALUES (1,1, to_date('25/02/2020','dd/mm/yyyy'),5000);
 
CREATE TABLE THAMSO (
	SoLuongNhapToiThieu NUMBER(8,0),
	SoLuongTonDeNhapToiDa NUMBER(8,0),
	TongNoToiDa NUMBER(12,0),
	LuongTonSauKhiBanToiThieu NUMBER(8,0),
	TiLeTinhDonGiaBan NUMBER(8,0),
	ChoPhepVuotTongNo NUMBER(1,0)
);

INSERT INTO THAMSO(SoLuongNhapToiThieu, SoLuongTonDeNhapToiDa, TongNoToiDa, LuongTonSauKhiBanToiThieu, TiLeTinhDonGiaBan, ChoPhepVuotTongNo)
VALUES (150, 300, 20000, 20, 100, 0);

ALTER TABLE TACGIA
 ADD CONSTRAINT TACGIA_PK PRIMARY KEY (MaTacGia)
/

ALTER TABLE THELOAI
 ADD CONSTRAINT THELOAI_PK PRIMARY KEY (MaTheLoai)
/

ALTER TABLE DAUSACH
 ADD CONSTRAINT DAUSACH_PK PRIMARY KEY (MaDauSach)
 ADD CONSTRAINT DAUSACH_THELOAI_FK FOREIGN KEY (MaTheLoai) REFERENCES THELOAI(MaTheLoai)
/

ALTER TABLE SACH
 ADD CONSTRAINT SACH_PK PRIMARY KEY (MaSach)
 ADD CONSTRAINT SACH_DAUSACH_FK FOREIGN KEY (MaDauSach) REFERENCES DAUSACH(MaDauSach)
/

ALTER TABLE PHIEUNHAPSACH
 ADD CONSTRAINT PHIEUNHAPSACH_PK PRIMARY KEY (MaPhieuNhapSach)
/

ALTER TABLE KHACHHANG
 ADD CONSTRAINT KHACHHANG_PK PRIMARY KEY (MaKhachHang)
/

ALTER TABLE HOADON
 ADD CONSTRAINT HOADON_PK PRIMARY KEY (MaHoaDon)
 ADD CONSTRAINT HOADON_KHACHHANG_FK FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang)
/

ALTER TABLE PHIEUTHU
 ADD CONSTRAINT PHIEUTHU_PK PRIMARY KEY (MaPhieuThu)
 ADD CONSTRAINT PHIEUTHU_KHACHHANG_FK FOREIGN KEY (MaKhachHang) REFERENCES KHACHHANG(MaKhachHang)
/

ALTER TABLE CHITIETHOADON
 ADD CONSTRAINT CHITIETHOADON_PK PRIMARY KEY (MaHoaDon, MaSach)
 ADD CONSTRAINT CHITIETHOADON_HOADON_FK FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon)
 ADD CONSTRAINT CHITIETHOADON_SACH_FK FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
/

ALTER TABLE CHITIETPHIEUNHAPSACH
 ADD CONSTRAINT CHITIETPHIEUNHAPSACH_PK PRIMARY KEY (MaPhieuNhapSach, MaSach)
 ADD CONSTRAINT CHITIETPHIEUNHAPSACH_PHIEUNHAPSACH_FK FOREIGN KEY (MaPhieuNhapSach) REFERENCES PHIEUNHAPSACH(MaPhieuNhapSach)
 ADD CONSTRAINT CHITIETPHIEUNHAPSACH_SACH_FK FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
/

ALTER TABLE CHITIETTACGIA 
 ADD CONSTRAINT CHITIETTACGIA_PK PRIMARY KEY (MaTacGia, MaDauSach)
 ADD CONSTRAINT CHITIETTACGIA_TACGIA_FK FOREIGN KEY (MaTacGia) REFERENCES TACGIA(MaTacGia)
 ADD CONSTRAINT CHITIETTACGIA_DAUSACH_FK FOREIGN KEY (MaDauSach) REFERENCES DAUSACH(MaDauSach)
/
